spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chufala_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: XGX123456@@

# mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


alipay:
  appId: 9021000153613249
  merchantPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+QgqPnM8B/wmF0mNoY3XkQmm7WyNtUvrPHpEBfFbGIUlHrZXUGKyuKLx1RxKR9whUL86hqzCQh7wJ2hHr6httJAMVnkOFuOWMJjhJoTi4SLoJtgYy+jdm0KgNPs1V6E2jNaP6yMz+KuKW0G8CO9qTub5EtQJlcNnAbi2wZwiBdo9WI75EYxSGZ6vK3nMiNbYzn8kjF8WJVsAZxODWaxb9H++sYm8SfY3D3oopNki+3jUzyYfFVtXQ1hwIozFWWO+c5AXTm+DBQ2UP0+XuDK7k54GNtgaMHpJAWxm/+9ssC+WRtizZMaK39YFtKwIT6h/mipXQTD6QdTRzXys6w+LzAgMBAAECggEBALDmpvsxSikJAcmz/UoqcIt0VOsnqqET7rB2M022VtiSSpijBhTXfHfS2KgTFWky0EO2z+HyUo2QJ37hjJhWbHnmahfHt/C2InlVcDDF/v8aYCB3ZvwvOyQWDquCIVonTUjbr0SXQENzjIu98fmZvXpt0kQAKeI4M7+Asmq64mW8Qa2EYoilR94ml476P0dHr+7+spTG71r3RSHe9vSccfMEEW0jj79v4RgXB/507AUWM2kA2LzNTV8hJfULDENj9jtiHNODwKV2cgteJeKhiw8aeu8Az1Q3aT8hxbJA5f8wRG7K+l324sCRmUi77+eJQ9GCyJTfZ/uj16rXwOylmMECgYEA+b8iaOuhRpcIGhVv1r3uz22HVpgkoCR+CJBPr35VHL/zM8puaGQJOymg6euH0aySLpm/2h6v0OGvd9HW70Q3snBTon4qi6DlWaoJAGE3xIiE5fm/BV+7ZZ4AS3+ocL9dy53Ro0I0JbZl+vPgG0dPcUpApIKoO6w+MRZP7AfIifcCgYEAwwWWSdTPC1MH01t8mX6ysF3HYDYUowzUjIvTqg1+PR+KNzBozAVnC3xlN48yRPO0E8egm/LrZ47eBkr1hkUlvFp49i58xpXeTHUEQxSuiy1o/CFo2GsKOM6JtB7BnmI8JsuZFI8nber9nuXT7ENOcVRfEunsN3oPvm/ZdONND+UCgYEAnIn3EXiP7+T+yQqivSDzrMRkThyy6EW3UbrSl5dB1fFiiRXbOkdpmdGv8K8WxI+8WMU6AYe2f+DV0O6QIAzMNGY/pdwa4sYIu7jeR4SoJeHEGzn9R2sH1NvCJ5Buja0FJ3lWS1RVx0Waij+OOsrpuoLmHbdfp3eAy9fGZJVEV2UCgYBLF9Sluza6Ao+p17ljlUCS3plNt6U8n00cjR7EhQuN154t4AsKPC5QYubKfO37VOeLEjwKsH/qUT22qJhfyjJck22uRXowMTb2s7wfZFBNMQASzX6EjrrR4t1tKMafCO5mddEM9I5XKbvculxexg/nXXh6XO5i8jIrvv+5nWhn7QKBgDUpmNDvyKnaN7YThouzHhnEzZyggWG1ELsH9wzT036/vrXDfIVfl6L80XQC+cAX0tAOw3sAz/AZ3Wqou0MjWWKuFXd1xub/P0hFDF+aLa/oudE45/PnEbO2S5fHO5Dab5bJD+nCfNf4gM3+egLWN0Cf3RvjWUyLfyhIQMS3KZcL
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuvIiEMs3gz781amoqbFAdrSw9gVB7KWAZDaz5uzgl5X2AJyf5whusMTtsowM2b0FnmbWXHU6d/RT9aHUmT19xWhbys3YqlH/VbM5c7e1WWPfCwb9Jv7SCjemVS6DVKGN2TLb1BxP0OLPK29XBrA6sSXPFzW7OpVKyoqleAoJlN/TYnHRuY3T+kvHqxDKkKi6S9c5DtE7PybdmFmxQIaxW8R7EpiurKz3BMHwmQg0dq0sd5fX15x2bPmfpJZXucUZfAqFo//KuZlWwzK4ShkpZkj4Gb3WO5RXjzmg2vO4QJfY8l1qIw7nzHwOuaKvOjJsYY3DBT+6S0wZUuxxY5dd2QIDAQAB
  notifyUrl: http://3fedab06.r9.vip.cpolar.cn/alipay/notify
  returnUrl: http://member.zyz.com/memberOrder.html
  signType: RSA2
  charset: utf-8
  # 我的支付宝网关地址
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do




